# commintlint配置文件 https://commitlint.js.org/#/reference-configuration
extends:
  - '@commitlint/config-conventional'
defaultIgnores: true # 是否使用commitlint默认的忽略规则
rules:
  type-empty:
    - 2
    - never
  subject-empty:
    - 0
    - never
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
  header-max-length:
    - 0
    - always
    - 100
